[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"
buildCommand = "cd client && npm install --include=dev && npm run build && mkdir -p ../server/public && cp -r dist/* ../server/public/ && cd ../server && npm install --omit=dev && npx prisma generate"

[deploy]
startCommand = "cd server && npx prisma migrate deploy && node src/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
