import { BRAND } from './constants.js';

export const styles = {
  page: {
    fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
    minHeight: "100vh",
    background: BRAND.light,
    color: BRAND.dark,
  },
  nav: {
    background: BRAND.gradient,
    padding: "0",
    position: "sticky",
    top: 0,
    zIndex: 100,
    boxShadow: "0 2px 12px rgba(0,0,0,0.15)",
  },
  navInner: {
    maxWidth: 1100,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 24px",
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    color: "#fff",
    fontWeight: 800,
    fontSize: 22,
    letterSpacing: "-0.5px",
    cursor: "pointer",
  },
  navLinks: {
    display: "flex",
    gap: 4,
  },
  navBtn: (active) => ({
    background: active ? "rgba(255,255,255,0.18)" : "transparent",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: active ? 700 : 500,
    display: "flex",
    alignItems: "center",
    gap: 6,
    transition: "all 0.2s",
  }),
  container: {
    maxWidth: 1100,
    margin: "0 auto",
    padding: "28px 24px",
  },
  card: {
    background: BRAND.white,
    borderRadius: 14,
    boxShadow: "0 1px 8px rgba(0,0,0,0.07)",
    padding: 28,
    marginBottom: 20,
    border: "1px solid #e2e8f0",
  },
  heading: {
    fontSize: 26,
    fontWeight: 800,
    color: BRAND.primary,
    marginBottom: 6,
  },
  subheading: {
    fontSize: 15,
    color: BRAND.muted,
    marginBottom: 24,
    lineHeight: 1.5,
  },
  label: {
    display: "block",
    fontSize: 13,
    fontWeight: 600,
    color: BRAND.primary,
    marginBottom: 6,
  },
  input: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid #d1d9e6",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
    transition: "border 0.2s",
  },
  textarea: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid #d1d9e6",
    fontSize: 14,
    outline: "none",
    minHeight: 90,
    resize: "vertical",
    boxSizing: "border-box",
    fontFamily: "inherit",
  },
  select: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid #d1d9e6",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
    background: "#fff",
  },
  btnPrimary: {
    background: BRAND.accent,
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "11px 24px",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    transition: "all 0.2s",
  },
  btnSecondary: {
    background: "transparent",
    color: BRAND.primary,
    border: `2px solid ${BRAND.primary}`,
    borderRadius: 8,
    padding: "9px 22px",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    transition: "all 0.2s",
  },
  btnDanger: {
    background: "transparent",
    color: BRAND.danger,
    border: "none",
    padding: "6px 10px",
    cursor: "pointer",
    borderRadius: 6,
    display: "inline-flex",
    alignItems: "center",
  },
  badge: (color) => ({
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: 20,
    fontSize: 11,
    fontWeight: 700,
    background: color + "18",
    color: color,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  }),
  grid2: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 16,
  },
  grid3: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: 16,
  },
  statCard: {
    background: BRAND.white,
    borderRadius: 14,
    padding: "22px 24px",
    boxShadow: "0 1px 8px rgba(0,0,0,0.07)",
    border: "1px solid #e2e8f0",
    textAlign: "center",
  },
  statNum: {
    fontSize: 32,
    fontWeight: 800,
    color: BRAND.primary,
  },
  statLabel: {
    fontSize: 12,
    color: BRAND.muted,
    fontWeight: 600,
    textTransform: "uppercase",
    marginTop: 4,
    letterSpacing: "0.5px",
  },
  modal: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(0,0,0,0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: 20,
  },
  modalContent: {
    background: BRAND.white,
    borderRadius: 16,
    padding: 32,
    maxWidth: 600,
    width: "100%",
    maxHeight: "85vh",
    overflowY: "auto",
    boxShadow: "0 20px 60px rgba(0,0,0,0.2)",
  },
  stepIndicator: (active, completed) => ({
    width: 36,
    height: 36,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
    fontWeight: 700,
    background: completed ? BRAND.success : active ? BRAND.accent : "#e2e8f0",
    color: completed || active ? "#fff" : BRAND.muted,
    transition: "all 0.3s",
    flexShrink: 0,
  }),
  stepLine: (completed) => ({
    flex: 1,
    height: 3,
    background: completed ? BRAND.success : "#e2e8f0",
    borderRadius: 3,
    margin: "0 6px",
    transition: "all 0.3s",
  }),
  tag: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    background: BRAND.primary + "10",
    color: BRAND.primary,
    padding: "4px 10px",
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 600,
  },
};
